### ISSUE TITLE
Path to ledger binary/library

### ISSUE THREAD

**Issue by arnuschky** [slashdotdash/node-ledger#5]
I assume that ledger-cli uses the orginal binary or library. Where can I specify the path to these?  (I can't get a grasp on this js code, sorry.)

**Comment by slashdotdash** [comment]
You should be able to proved the path to the Ledger binary as follows.

```js
var ledger = new Ledger({ 
  binary: '/usr/local/bin/ledger',
  file: 'path/to/ledger/journal/file.dat'
});
```
